# Generated by Django 3.0.3 on 2020-04-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200411_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
