# Generated by Django 3.0.5 on 2020-05-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200418_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
