# Generated by Django 3.0.3 on 2020-03-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_auto_20200330_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Second_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(choices=[('g', 'Male'), ('b', 'Female')], max_length=1)),
                ('birth', models.DateField()),
                ('Password1', models.CharField(max_length=50)),
                ('Password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post'),
        ),
    ]
