# Generated by Django 3.0.3 on 2020-03-30 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_auto_20200330_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birth',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post'),
        ),
    ]
