# Generated by Django 3.0.3 on 2020-05-01 02:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0040_auto_20200430_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_update',
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post'),
        ),
    ]
