# Generated by Django 3.0.3 on 2020-05-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0053_auto_20200504_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='post',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
