# Generated by Django 3.0.3 on 2020-06-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0056_auto_20200604_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post'),
        ),
    ]
